enum Actions {

    SAVE_PRODUCT_TO_CART = 'SAVE_PRODUCT_TO_CART',
    DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART',
    SAVE_CENTER_TO_CART = 'SAVE_CENTER_TO_CART',
    SAVE_SUPPLIER_TO_CART = 'SAVE_SUPPLIER_TO_CART',
    CLEAN_PRODUCTS_IN_CART = 'CLEAN_PRODUCTS_IN_CART',
    CLEAN_CART = 'CLEAN_CART'
};

export default Actions;
